# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  major: 2
  minor: 1

name: $(major).$(minor)$(Rev:.r)

stages:
- stage:
  # this stage runs only if the branch is not master
  displayName: Build_Branch_Version_Number
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: Build_Branch_Version_Number
    variables:
       brpatch: $[counter(variables['build.sourcebranchname'], 0)]
    steps:
      - bash: |
           echo "##vso[build.updatebuildnumber]$(major).$(minor)-$(Build.SourceBranchName).$(brpatch)"
        condition: ne(variables['Build.Reason'], 'PullRequest')
        name: SetBranchBuildName

- stage: Build_Steps
  displayName: Build_Steps
  jobs:  
  - job: Build_Steps
    displayName: Build_Steps
    steps:
    - script: echo 'Hello, world!'
      displayName: 'Run a one-line script'
    - script: |
        echo 'Add other tasks to build, test, and deploy your project.'
        echo 'See https://aka.ms/yaml'
      displayName: 'Run a multi-line script'
