# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  major: 1
  minor: 1

name: $(major).$(minor)$(Rev:.r)

steps:
- script: echo 'Hello, world!'
  displayName: 'Run a one-line script'
- script: |
    echo 'Add other tasks to build, test, and deploy your project.'
    echo 'See https://aka.ms/yaml'
  displayName: 'Run a multi-line script'
